#!/usr/bin/env python3
"""
Restore the damaged book HTML by reconstructing sections 1-9 from
the individual section design files, then re-running build-book.py.
"""
import re
from pathlib import Path

BASE     = Path(r'C:\Users\zande\Documents\AI Workspace\Analyzing Islam')
SEC_DIR  = BASE / 'book-design' / 'vol1-quran'
BOOK_FILE = SEC_DIR / 'Analyzing Islam Vol I — The Quran.html'

# Read current (damaged) book file - has CSS preamble + sections 12-13
current_html = BOOK_FILE.read_text(encoding='utf-8', errors='ignore')
print(f'Current HTML length: {len(current_html):,}')

# Find the true CSS/head preamble — ends at </style> closing the main block
# The preamble is everything up to and including the first </style>
style_end = current_html.find('</style>')
if style_end == -1:
    raise RuntimeError('Could not find </style> in current HTML')
# Include one more closing tag: </head> if present, or just after </style>
head_end = current_html.find('</head>', style_end)
if head_end != -1:
    preamble_end = head_end + len('</head>') + 1
else:
    preamble_end = style_end + len('</style>') + 1

css_preamble = current_html[:preamble_end]
print(f'CSS preamble ends at: {preamble_end}')

# Find where section 12 starts
sec12_div = current_html.find('<div class="section-divider">Section 12')
sec12_comment = current_html.rfind('<!--', 0, sec12_div)
# Find the LAST occurrence of section 12 (in case it appears multiple times)
# Actually find the one that's the actual section 12 block
# Find the comment block just before section-divider Section 12
print(f'Section 12 comment starts at: {sec12_comment}')

sections_12_onwards = current_html[sec12_comment:]
print(f'CSS preamble: {len(css_preamble):,} chars')
print(f'Sections 12+: {len(sections_12_onwards):,} chars')

# ── Extract body content from each section file ────────────────────────────────
sep = '═' * 54  # ══...══

SECTION_LABELS = {
    1:  'COVERS (FRONT + BACK)',
    2:  'HALF-TITLE',
    3:  'TITLE PAGE',
    4:  'COPYRIGHT',
    5:  'TABLE OF CONTENTS',
    6:  'FOREWORD',
    7:  'ABBREVIATIONS & REFERENCE GUIDE',
    8:  'PART OPENER',
    9:  'SOURCE INTRODUCTION',
}

SECTION_FILES = {
    1:  None,  # Covers are in sec 13 — skip for front
    2:  SEC_DIR / '01-half-title.html',
    3:  SEC_DIR / '02-title.html',
    4:  SEC_DIR / '03-copyright.html',
    5:  SEC_DIR / '04-toc.html',
    6:  SEC_DIR / '05-foreword.html',
    7:  SEC_DIR / '06-abbreviations.html',
    8:  SEC_DIR / '07-part-opener.html',
    9:  SEC_DIR / '08-source-introduction.html',
}

def extract_body_content(filepath):
    """Extract everything between <body> and </body> tags."""
    html = filepath.read_text(encoding='utf-8', errors='ignore')
    # Find body content
    body_start = html.find('<body')
    body_end   = html.rfind('</body>')
    if body_start == -1 or body_end == -1:
        # No body tags - take everything after </head>
        head_end = html.find('</head>')
        if head_end != -1:
            content = html[head_end+7:].strip()
        else:
            content = html
    else:
        # Get content inside body
        body_tag_end = html.find('>', body_start) + 1
        content = html[body_tag_end:body_end].strip()
    return content

def make_section_block(sec_num, content):
    """Wrap section content in the proper comment marker."""
    label = SECTION_LABELS.get(sec_num, f'SECTION {sec_num}')
    comment = (
        f'<!-- {sep}\n'
        f'     SECTION {sec_num} — {label}\n'
        f'     {sep} -->\n'
    )
    divider = f'<div class="section-divider">Section {sec_num} — {label.title()}</div>\n'
    return comment + divider + '\n' + content + '\n\n\n\n'

# Build front matter sections 2-9
front_sections = []
for sec in range(2, 10):
    filepath = SECTION_FILES.get(sec)
    if filepath and filepath.exists():
        content = extract_body_content(filepath)
        block   = make_section_block(sec, content)
        front_sections.append(block)
        print(f'Section {sec}: extracted {len(content):,} chars from {filepath.name}')
    else:
        print(f'Section {sec}: FILE NOT FOUND — skipping')

# Add section 10 placeholder (build-book.py will fill this in)
sec10_placeholder = (
    f'<!-- {sep}\n'
    f'     SECTION 10 — CHAPTERS & ENTRIES\n'
    f'     {sep} -->\n'
    '<div class="section-divider">Section 10 — The Quran: 20 Chapters</div>\n\n'
)
# Section 11 (chapter entries) will be generated by build-book.py

# Also add section 11 placeholder marker (general index section)
sec11_placeholder = (
    f'\n\n<!-- {sep}\n'
    f'     SECTION 11 — CHAPTER OPENERS (see section 10)\n'
    f'     {sep} -->\n\n'
)

# Assemble the restored HTML
# Note: section 1 (Covers/Back cover) goes AFTER everything in section 13
# For now, skip covers (they come at the end)
restored = (
    css_preamble
    + '\n'.join(front_sections)
    + '\n\n'
    + sec10_placeholder
    + '\n\n'
    + sections_12_onwards
)

BOOK_FILE.write_text(restored, encoding='utf-8')
print(f'\nRestored HTML: {len(restored):,} chars')

# Verify section markers
sec_matches = list(re.finditer(r'SECTION (\d+)', restored))
print(f'Section markers found: {[m.group() for m in sec_matches]}')
