#!/usr/bin/env python3
"""Find every <a href="../read/{slug}.html#{anchor}">...</a> whose anchor does
not exist in the corresponding reader, and unwrap the tag — leaving the plain
citation text in place. Operates only on site/catalog/*.html; category pages
are regenerated by build-category-pages.py afterwards.
"""
import os
import re
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).parent
CATALOG_DIR = ROOT / "site" / "catalog"
READ_DIR = ROOT / "site" / "read"


def valid_anchors(slug: str) -> set[str]:
    """Return the set of id="..." values defined in the reader for this slug."""
    path = READ_DIR / f"{slug}.html"
    if not path.exists():
        return set()
    t = path.read_text(encoding="utf-8")
    if slug == "quran":
        return set(re.findall(r'id="(s\d+v\d+)"', t))
    return set(re.findall(r'id="(h\d+)"', t))


# Matches a reader-anchored <a ...>...</a>. Captures the slug and anchor.
LINK_RE = re.compile(
    r'<a\s+([^>]*?)href="\.\./read/(?P<slug>[a-z-]+)\.html#(?P<anchor>[^"]+)"'
    r'([^>]*?)>(?P<text>.*?)</a>',
    re.DOTALL,
)


def process_file(path: Path, valid: dict[str, set[str]]) -> int:
    """Unwrap broken-anchor links in `path`. Returns number of links removed."""
    original = path.read_text(encoding="utf-8")
    removed = 0

    def repl(m: re.Match) -> str:
        nonlocal removed
        slug = m.group("slug")
        anchor = m.group("anchor")
        text = m.group("text")
        if slug in valid and anchor not in valid[slug]:
            removed += 1
            return text
        return m.group(0)

    new = LINK_RE.sub(repl, original)
    if new != original:
        path.write_text(new, encoding="utf-8")
    return removed


def main() -> None:
    # Build the set of valid anchors for every reader slug we care about.
    slugs = ["quran", "bukhari", "muslim", "abu-dawud", "tirmidhi",
             "nasai", "ibn-majah"]
    valid = {s: valid_anchors(s) for s in slugs}

    total = 0
    for path in sorted(CATALOG_DIR.glob("*.html")):
        removed = process_file(path, valid)
        if removed:
            print(f"  {path.name}: unwrapped {removed} broken link(s)")
            total += removed
    print(f"\nTotal broken links unwrapped: {total}")
    print("Next: run  python build-category-pages.py  to propagate.")


if __name__ == "__main__":
    main()
